version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
      # no semver support for github-actions
      # => no specific configuration for this
      include:
        - "*"
